<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('verification_profiles', function (Blueprint $table): void {
            $table->boolean('is_provider_in_network')->nullable()->after('plan_type');
            $table->string('plan_renewal_month')->nullable()->after('is_provider_in_network');
            $table->date('future_termination_date')->nullable()->after('plan_renewal_month');
            $table->text('deductible_applies_notes')->nullable()->after('family_deductible_remaining');
            $table->text('plan_provisions')->nullable()->after('coverage_implant');
            $table->text('missing_tooth_clause')->nullable()->after('waiting_periods');
            $table->string('crowns_paid_on')->nullable()->after('missing_tooth_clause');
            $table->string('prosthetic_replacement_period')->nullable()->after('crowns_paid_on');
            $table->text('history_exams')->nullable()->after('service_history');
            $table->text('history_prophylaxis')->nullable()->after('history_exams');
            $table->text('history_bitewings')->nullable()->after('history_prophylaxis');
            $table->text('history_full_mouth_xray')->nullable()->after('history_bitewings');
            $table->text('history_basic_or_major')->nullable()->after('history_full_mouth_xray');
            $table->text('frequency_regular_oral_exams')->nullable()->after('history_basic_or_major');
            $table->text('frequency_limited_exam')->nullable()->after('frequency_regular_oral_exams');
            $table->text('frequency_comprehensive_exam')->nullable()->after('frequency_limited_exam');
            $table->text('frequency_exam_shared')->nullable()->after('frequency_comprehensive_exam');
            $table->text('frequency_oral_cancer_screening')->nullable()->after('frequency_exam_shared');
            $table->text('frequency_oral_cancer_conjunction')->nullable()->after('frequency_oral_cancer_screening');
            $table->text('frequency_prophylaxis')->nullable()->after('frequency_oral_cancer_conjunction');
            $table->text('frequency_bitewings')->nullable()->after('frequency_prophylaxis');
            $table->text('frequency_full_mouth_pano_shared')->nullable()->after('frequency_bitewings');
            $table->text('frequency_pas')->nullable()->after('frequency_full_mouth_pano_shared');
            $table->text('frequency_sealants')->nullable()->after('frequency_pas');
            $table->text('frequency_sealants_guideline')->nullable()->after('frequency_sealants');
            $table->text('frequency_caries_arresting')->nullable()->after('frequency_sealants_guideline');
            $table->text('frequency_fluoride')->nullable()->after('frequency_caries_arresting');
            $table->text('basic_scaling_root_planing')->nullable()->after('frequency_fluoride');
            $table->text('basic_all_quads_same_visit')->nullable()->after('basic_scaling_root_planing');
            $table->text('basic_perio_maintenance_share_freq')->nullable()->after('basic_all_quads_same_visit');
            $table->text('basic_fmd')->nullable()->after('basic_perio_maintenance_share_freq');
            $table->text('basic_root_canal')->nullable()->after('basic_fmd');
            $table->text('basic_simple_extraction')->nullable()->after('basic_root_canal');
            $table->text('basic_surgical_extraction')->nullable()->after('basic_simple_extraction');
            $table->text('basic_posterior_composites')->nullable()->after('basic_surgical_extraction');
            $table->text('basic_composites_downgrade')->nullable()->after('basic_posterior_composites');
            $table->text('basic_occlusal_guard')->nullable()->after('basic_composites_downgrade');
            $table->text('major_crowns_downgrade')->nullable()->after('basic_occlusal_guard');
            $table->text('major_pf_high_noble')->nullable()->after('major_crowns_downgrade');
            $table->text('major_hydroxyapatite')->nullable()->after('major_pf_high_noble');
            $table->text('major_dentures')->nullable()->after('major_hydroxyapatite');
            $table->text('major_implant')->nullable()->after('major_dentures');
            $table->text('major_implant_abutment')->nullable()->after('major_implant');
            $table->text('major_implant_crown')->nullable()->after('major_implant_abutment');
            $table->text('major_bone_graft_same_time_implant')->nullable()->after('major_implant_crown');
            $table->text('major_bone_grafts')->nullable()->after('major_bone_graft_same_time_implant');
            $table->text('ortho_benefit')->nullable()->after('ortho_information');
            $table->text('ortho_retention')->nullable()->after('ortho_benefit');
            $table->string('ortho_lifetime_maximum')->nullable()->after('ortho_retention');
            $table->string('ortho_remaining_maximum')->nullable()->after('ortho_lifetime_maximum');
            $table->string('ortho_deductibles')->nullable()->after('ortho_remaining_maximum');
            $table->string('ortho_age_limit')->nullable()->after('ortho_deductibles');
            $table->date('verification_date')->nullable()->after('ortho_age_limit');
            $table->string('verified_by')->nullable()->after('verification_date');
            $table->string('insurance_representative_name')->nullable()->after('verified_by');
        });
    }

    public function down(): void
    {
        Schema::table('verification_profiles', function (Blueprint $table): void {
            $table->dropColumn([
                'is_provider_in_network',
                'plan_renewal_month',
                'future_termination_date',
                'deductible_applies_notes',
                'plan_provisions',
                'missing_tooth_clause',
                'crowns_paid_on',
                'prosthetic_replacement_period',
                'history_exams',
                'history_prophylaxis',
                'history_bitewings',
                'history_full_mouth_xray',
                'history_basic_or_major',
                'frequency_regular_oral_exams',
                'frequency_limited_exam',
                'frequency_comprehensive_exam',
                'frequency_exam_shared',
                'frequency_oral_cancer_screening',
                'frequency_oral_cancer_conjunction',
                'frequency_prophylaxis',
                'frequency_bitewings',
                'frequency_full_mouth_pano_shared',
                'frequency_pas',
                'frequency_sealants',
                'frequency_sealants_guideline',
                'frequency_caries_arresting',
                'frequency_fluoride',
                'basic_scaling_root_planing',
                'basic_all_quads_same_visit',
                'basic_perio_maintenance_share_freq',
                'basic_fmd',
                'basic_root_canal',
                'basic_simple_extraction',
                'basic_surgical_extraction',
                'basic_posterior_composites',
                'basic_composites_downgrade',
                'basic_occlusal_guard',
                'major_crowns_downgrade',
                'major_pf_high_noble',
                'major_hydroxyapatite',
                'major_dentures',
                'major_implant',
                'major_implant_abutment',
                'major_implant_crown',
                'major_bone_graft_same_time_implant',
                'major_bone_grafts',
                'ortho_benefit',
                'ortho_retention',
                'ortho_lifetime_maximum',
                'ortho_remaining_maximum',
                'ortho_deductibles',
                'ortho_age_limit',
                'verification_date',
                'verified_by',
                'insurance_representative_name',
            ]);
        });
    }
};
