<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\HtmlString;

class SaasSetting extends Model
{
    protected $fillable = [
        'platform_name',
        'company_name',
        'logo_path',
        'support_email',
        'support_phone',
        'address',
        'bank_account_name',
        'bank_account_type',
        'bank_name',
        'bank_account_number',
        'bank_routing_number',
        'bank_swift_code',
        'bank_ifsc_code',
        'bank_branch',
        'bank_payment_notes',
        'invoice_logo_path',
        'invoice_signature_path',
        'invoice_language',
        'invoice_number_style',
        'invoice_due_after_days',
        'invoice_show_status',
        'invoice_show_tax_number',
        'invoice_show_tax_message',
        'invoice_tax_number_value',
        'invoice_tax_message_text',
        'invoice_show_authorised_signatory',
        'invoice_show_client_name',
        'invoice_show_client_email',
        'invoice_show_client_phone',
        'invoice_show_client_address',
        'invoice_terms_conditions',
        'invoice_template_style',
        'invoice_show_payment_instructions',
        'invoice_show_invoice_notice',
        'invoice_compact_layout',
        'invoice_prefix',
        'invoice_number_separator',
        'invoice_number_digits',
        'invoice_include_period_prefix',
        'invoice_unit_label',
        'invoice_quantity_precision',
        'quickbooks_enabled',
        'quickbooks_company_id',
        'quickbooks_client_id',
        'quickbooks_client_secret',
        'quickbooks_auto_sync',
        'default_country',
        'default_timezone',
        'default_currency',
        'maintenance_mode',
        'notify_database_on_organization_onboarded',
        'notify_database_on_incomplete_onboarding',
        'notify_database_on_settings_updated',
        'notify_database_on_user_created',
        'notify_database_on_user_updated',
        'notify_database_on_user_deleted',
        'notify_database_on_invoice_created',
        'notify_database_on_invoice_updated',
        'notify_database_on_invoice_deleted',
        'notify_database_on_invoice_sent',
        'email_enabled',
        'email_mailer',
        'email_host',
        'email_port',
        'email_username',
        'email_password',
        'email_encryption',
        'email_from_address',
        'email_from_name',
        'email_on_organization_onboarded',
        'email_on_incomplete_onboarding',
        'email_on_settings_updated',
        'email_on_user_created',
        'email_on_user_updated',
        'email_on_user_deleted',
        'email_send_user_verification',
        'email_on_invoice_created',
        'email_on_invoice_updated',
        'email_on_invoice_deleted',
        'email_on_invoice_sent',
        'stripe_enabled',
        'stripe_environment',
        'stripe_publishable_key',
        'stripe_secret_key',
        'stripe_webhook_secret',
        'paypal_enabled',
        'paypal_environment',
        'paypal_client_id',
        'paypal_client_secret',
        'paypal_webhook_id',
        'billing_automation_enabled',
        'billing_mark_overdue_enabled',
        'billing_send_pre_due_reminders',
        'billing_pre_due_days',
        'billing_send_overdue_reminders',
        'billing_overdue_reminder_days',
        'verification_notify_admin_all',
        'verification_notify_assigned_user',
        'verification_notify_clinic_self_service',
        'verification_notify_clinic_workspace',
        'verification_notify_on_managed_service_requested',
        'verification_notify_on_clinic_self_service_created',
        'verification_notify_on_verification_request_created',
        'verification_notify_on_admin_import_created',
        'verification_notify_on_assignment_changed',
        'verification_notify_on_status_changed',
        'verification_notify_on_outcome_changed',
        'verification_notify_on_clinic_verification_updated',
        'verification_notify_on_verification_profile_saved',
        'verification_notify_on_verification_pdf_download',
        'verification_notify_on_verification_pdf_preview',
        'verification_notify_on_urgent_flagged',
        'verification_notify_on_urgent_assigned',
        'verification_notify_on_sla_alert',
        'verification_round_robin_enabled',
        'verification_round_robin_last_user_id',
        'verification_inbox_enabled',
        'verification_inbox_provider',
        'verification_inbox_host',
        'verification_inbox_port',
        'verification_inbox_protocol',
        'verification_inbox_encryption',
        'verification_inbox_validate_certificate',
        'verification_inbox_username',
        'verification_inbox_password',
        'verification_inbox_folder_inbox',
        'verification_inbox_folder_spam',
        'verification_inbox_sync_frequency_minutes',
        'verification_inbox_sync_window_days',
        'verification_inbox_retention_mode',
        'verification_inbox_retention_days',
        'verification_inbox_keep_latest_count',
        'verification_inbox_spam_retention_days',
        'verification_inbox_preserve_flagged',
        'verification_inbox_auto_cleanup_enabled',
        'verification_inbox_last_synced_at',
        'verification_inbox_last_cleanup_at',
    ];

    protected function casts(): array
    {
        return [
            'maintenance_mode' => 'boolean',
            'notify_database_on_organization_onboarded' => 'boolean',
            'notify_database_on_incomplete_onboarding' => 'boolean',
            'notify_database_on_settings_updated' => 'boolean',
            'notify_database_on_user_created' => 'boolean',
            'notify_database_on_user_updated' => 'boolean',
            'notify_database_on_user_deleted' => 'boolean',
            'notify_database_on_invoice_created' => 'boolean',
            'notify_database_on_invoice_updated' => 'boolean',
            'notify_database_on_invoice_deleted' => 'boolean',
            'notify_database_on_invoice_sent' => 'boolean',
            'email_enabled' => 'boolean',
            'email_port' => 'integer',
            'email_password' => 'encrypted',
            'email_on_organization_onboarded' => 'boolean',
            'email_on_incomplete_onboarding' => 'boolean',
            'email_on_settings_updated' => 'boolean',
            'email_on_user_created' => 'boolean',
            'email_on_user_updated' => 'boolean',
            'email_on_user_deleted' => 'boolean',
            'email_send_user_verification' => 'boolean',
            'email_on_invoice_created' => 'boolean',
            'email_on_invoice_updated' => 'boolean',
            'email_on_invoice_deleted' => 'boolean',
            'email_on_invoice_sent' => 'boolean',
            'stripe_enabled' => 'boolean',
            'stripe_secret_key' => 'encrypted',
            'stripe_webhook_secret' => 'encrypted',
            'paypal_enabled' => 'boolean',
            'paypal_client_secret' => 'encrypted',
            'invoice_due_after_days' => 'integer',
            'invoice_show_status' => 'boolean',
            'invoice_show_tax_number' => 'boolean',
            'invoice_show_tax_message' => 'boolean',
            'invoice_show_authorised_signatory' => 'boolean',
            'invoice_show_client_name' => 'boolean',
            'invoice_show_client_email' => 'boolean',
            'invoice_show_client_phone' => 'boolean',
            'invoice_show_client_address' => 'boolean',
            'invoice_show_payment_instructions' => 'boolean',
            'invoice_show_invoice_notice' => 'boolean',
            'invoice_compact_layout' => 'boolean',
            'invoice_number_digits' => 'integer',
            'invoice_include_period_prefix' => 'boolean',
            'invoice_quantity_precision' => 'integer',
            'quickbooks_enabled' => 'boolean',
            'quickbooks_client_secret' => 'encrypted',
            'quickbooks_auto_sync' => 'boolean',
            'billing_automation_enabled' => 'boolean',
            'billing_mark_overdue_enabled' => 'boolean',
            'billing_send_pre_due_reminders' => 'boolean',
            'billing_pre_due_days' => 'integer',
            'billing_send_overdue_reminders' => 'boolean',
            'billing_overdue_reminder_days' => 'integer',
            'verification_notify_admin_all' => 'boolean',
            'verification_notify_assigned_user' => 'boolean',
            'verification_notify_clinic_self_service' => 'boolean',
            'verification_notify_clinic_workspace' => 'boolean',
            'verification_notify_on_managed_service_requested' => 'boolean',
            'verification_notify_on_clinic_self_service_created' => 'boolean',
            'verification_notify_on_verification_request_created' => 'boolean',
            'verification_notify_on_admin_import_created' => 'boolean',
            'verification_notify_on_assignment_changed' => 'boolean',
            'verification_notify_on_status_changed' => 'boolean',
            'verification_notify_on_outcome_changed' => 'boolean',
            'verification_notify_on_clinic_verification_updated' => 'boolean',
            'verification_notify_on_verification_profile_saved' => 'boolean',
            'verification_notify_on_verification_pdf_download' => 'boolean',
            'verification_notify_on_verification_pdf_preview' => 'boolean',
            'verification_notify_on_urgent_flagged' => 'boolean',
            'verification_notify_on_urgent_assigned' => 'boolean',
            'verification_notify_on_sla_alert' => 'boolean',
            'verification_round_robin_enabled' => 'boolean',
            'verification_round_robin_last_user_id' => 'integer',
            'verification_inbox_enabled' => 'boolean',
            'verification_inbox_port' => 'integer',
            'verification_inbox_validate_certificate' => 'boolean',
            'verification_inbox_password' => 'encrypted',
            'verification_inbox_sync_frequency_minutes' => 'integer',
            'verification_inbox_sync_window_days' => 'integer',
            'verification_inbox_retention_days' => 'integer',
            'verification_inbox_keep_latest_count' => 'integer',
            'verification_inbox_spam_retention_days' => 'integer',
            'verification_inbox_preserve_flagged' => 'boolean',
            'verification_inbox_auto_cleanup_enabled' => 'boolean',
            'verification_inbox_last_synced_at' => 'datetime',
            'verification_inbox_last_cleanup_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        static::saved(fn (): bool => Cache::forget('saas_settings.current'));
        static::deleted(fn (): bool => Cache::forget('saas_settings.current'));
    }

    public static function current(): self
    {
        if (! Schema::hasTable('saas_settings')) {
            return new static([
                'platform_name' => 'ProDental EMR',
                'default_country' => 'USA',
                'default_timezone' => 'America/New_York',
            'default_currency' => 'USD',
            'invoice_language' => 'en',
            'invoice_number_style' => 'prefixed_period_sequence',
            'invoice_due_after_days' => 3,
            'invoice_show_status' => true,
            'invoice_show_tax_number' => false,
            'invoice_show_tax_message' => false,
            'invoice_tax_number_value' => null,
            'invoice_tax_message_text' => null,
            'invoice_show_authorised_signatory' => false,
                'invoice_show_client_name' => true,
                'invoice_show_client_email' => true,
                'invoice_show_client_phone' => true,
                'invoice_show_client_address' => true,
                'invoice_template_style' => 'modern',
                'invoice_show_payment_instructions' => true,
                'invoice_show_invoice_notice' => true,
                'invoice_compact_layout' => true,
                'invoice_prefix' => 'INV',
                'invoice_number_separator' => '-',
                'invoice_number_digits' => 4,
                'invoice_include_period_prefix' => true,
                'invoice_unit_label' => 'Qty',
                'invoice_quantity_precision' => 2,
                'quickbooks_enabled' => false,
                'quickbooks_auto_sync' => false,
                'maintenance_mode' => false,
                'notify_database_on_organization_onboarded' => true,
                'notify_database_on_incomplete_onboarding' => true,
                'notify_database_on_settings_updated' => true,
                'notify_database_on_user_created' => true,
                'notify_database_on_user_updated' => true,
                'notify_database_on_user_deleted' => true,
                'notify_database_on_invoice_created' => true,
                'notify_database_on_invoice_updated' => true,
                'notify_database_on_invoice_deleted' => true,
                'notify_database_on_invoice_sent' => true,
                'email_enabled' => false,
                'email_mailer' => 'smtp',
                'email_encryption' => 'tls',
                'email_on_organization_onboarded' => false,
                'email_on_incomplete_onboarding' => false,
                'email_on_settings_updated' => false,
                'email_on_user_created' => false,
                'email_on_user_updated' => false,
                'email_on_user_deleted' => false,
                'email_send_user_verification' => true,
                'email_on_invoice_created' => false,
                'email_on_invoice_updated' => false,
                'email_on_invoice_deleted' => false,
                'email_on_invoice_sent' => true,
                'stripe_enabled' => false,
                'stripe_environment' => 'test',
                'paypal_enabled' => false,
                'paypal_environment' => 'sandbox',
                'billing_automation_enabled' => false,
                'billing_mark_overdue_enabled' => true,
                'billing_send_pre_due_reminders' => true,
                'billing_pre_due_days' => 3,
                'billing_send_overdue_reminders' => true,
                'billing_overdue_reminder_days' => 1,
                'verification_notify_admin_all' => true,
                'verification_notify_assigned_user' => true,
                'verification_notify_clinic_self_service' => true,
                'verification_notify_clinic_workspace' => false,
                'verification_notify_on_managed_service_requested' => true,
                'verification_notify_on_clinic_self_service_created' => true,
                'verification_notify_on_verification_request_created' => true,
                'verification_notify_on_admin_import_created' => true,
                'verification_notify_on_assignment_changed' => true,
                'verification_notify_on_status_changed' => true,
                'verification_notify_on_outcome_changed' => true,
                'verification_notify_on_clinic_verification_updated' => true,
                'verification_notify_on_verification_profile_saved' => false,
                'verification_notify_on_verification_pdf_download' => false,
                'verification_notify_on_verification_pdf_preview' => false,
                'verification_notify_on_urgent_flagged' => true,
                'verification_notify_on_urgent_assigned' => true,
                'verification_notify_on_sla_alert' => true,
                'verification_round_robin_enabled' => false,
                'verification_round_robin_last_user_id' => null,
                'verification_inbox_enabled' => false,
                'verification_inbox_protocol' => 'imap',
                'verification_inbox_encryption' => 'ssl',
                'verification_inbox_validate_certificate' => false,
                'verification_inbox_folder_inbox' => 'INBOX',
                'verification_inbox_folder_spam' => 'INBOX.Spam',
                'verification_inbox_sync_frequency_minutes' => 15,
                'verification_inbox_sync_window_days' => 90,
                'verification_inbox_retention_mode' => 'days',
                'verification_inbox_retention_days' => 90,
                'verification_inbox_keep_latest_count' => 5000,
                'verification_inbox_spam_retention_days' => 30,
                'verification_inbox_preserve_flagged' => true,
                'verification_inbox_auto_cleanup_enabled' => true,
            ]);
        }

        return Cache::remember(
            'saas_settings.current',
            now()->addMinutes(5),
            fn (): self => static::query()->firstOrCreate(
                ['id' => 1],
                [
                    'platform_name' => 'ProDental EMR',
                    'default_country' => 'USA',
                    'default_timezone' => 'America/New_York',
                    'default_currency' => 'USD',
                    'invoice_language' => 'en',
                    'invoice_number_style' => 'prefixed_period_sequence',
                    'invoice_due_after_days' => 3,
                    'invoice_show_status' => true,
                    'invoice_show_tax_number' => false,
                    'invoice_show_tax_message' => false,
                    'invoice_tax_number_value' => null,
                    'invoice_tax_message_text' => null,
                    'invoice_show_authorised_signatory' => false,
                    'invoice_show_client_name' => true,
                    'invoice_show_client_email' => true,
                    'invoice_show_client_phone' => true,
                    'invoice_show_client_address' => true,
                    'invoice_template_style' => 'modern',
                    'invoice_show_payment_instructions' => true,
                    'invoice_show_invoice_notice' => true,
                    'invoice_compact_layout' => true,
                    'invoice_prefix' => 'INV',
                    'invoice_number_separator' => '-',
                    'invoice_number_digits' => 4,
                    'invoice_include_period_prefix' => true,
                    'invoice_unit_label' => 'Qty',
                    'invoice_quantity_precision' => 2,
                    'quickbooks_enabled' => false,
                    'quickbooks_auto_sync' => false,
                    'maintenance_mode' => false,
                    'notify_database_on_organization_onboarded' => true,
                    'notify_database_on_incomplete_onboarding' => true,
                    'notify_database_on_settings_updated' => true,
                    'notify_database_on_user_created' => true,
                    'notify_database_on_user_updated' => true,
                    'notify_database_on_user_deleted' => true,
                    'notify_database_on_invoice_created' => true,
                    'notify_database_on_invoice_updated' => true,
                    'notify_database_on_invoice_deleted' => true,
                    'notify_database_on_invoice_sent' => true,
                    'email_enabled' => false,
                    'email_mailer' => 'smtp',
                    'email_encryption' => 'tls',
                    'email_on_organization_onboarded' => false,
                    'email_on_incomplete_onboarding' => false,
                    'email_on_settings_updated' => false,
                    'email_on_user_created' => false,
                    'email_on_user_updated' => false,
                    'email_on_user_deleted' => false,
                    'email_send_user_verification' => true,
                    'email_on_invoice_created' => false,
                    'email_on_invoice_updated' => false,
                    'email_on_invoice_deleted' => false,
                    'email_on_invoice_sent' => true,
                    'stripe_enabled' => false,
                    'stripe_environment' => 'test',
                    'paypal_enabled' => false,
                    'paypal_environment' => 'sandbox',
                    'billing_automation_enabled' => false,
                    'billing_mark_overdue_enabled' => true,
                    'billing_send_pre_due_reminders' => true,
                    'billing_pre_due_days' => 3,
                    'billing_send_overdue_reminders' => true,
                    'billing_overdue_reminder_days' => 1,
                    'verification_notify_admin_all' => true,
                    'verification_notify_assigned_user' => true,
                    'verification_notify_clinic_self_service' => true,
                    'verification_notify_clinic_workspace' => false,
                    'verification_notify_on_managed_service_requested' => true,
                    'verification_notify_on_clinic_self_service_created' => true,
                    'verification_notify_on_verification_request_created' => true,
                    'verification_notify_on_admin_import_created' => true,
                    'verification_notify_on_assignment_changed' => true,
                    'verification_notify_on_status_changed' => true,
                    'verification_notify_on_outcome_changed' => true,
                    'verification_notify_on_clinic_verification_updated' => true,
                    'verification_notify_on_verification_profile_saved' => false,
                    'verification_notify_on_verification_pdf_download' => false,
                    'verification_notify_on_verification_pdf_preview' => false,
                    'verification_notify_on_urgent_flagged' => true,
                    'verification_notify_on_urgent_assigned' => true,
                    'verification_notify_on_sla_alert' => true,
                    'verification_round_robin_enabled' => false,
                    'verification_round_robin_last_user_id' => null,
                ],
            ),
        );
    }

    public function brandName(): string
    {
        return $this->platform_name ?: 'ProDental EMR';
    }

    public function brandLogoUrl(): ?string
    {
        if (blank($this->logo_path)) {
            return null;
        }

        return Storage::disk('branding')->url($this->logo_path);
    }

    public function brandLogo(): ?HtmlString
    {
        $logoUrl = $this->brandLogoUrl();

        if (! $logoUrl) {
            return null;
        }

        return new HtmlString(sprintf(
            '<img src="%s" alt="%s" style="height: 2rem; width: auto;">',
            e($logoUrl),
            e($this->brandName()),
        ));
    }
}
