<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class VerificationProfile extends Model
{
    public const FORM_TYPE_OPTIONS = [
        'full_form' => 'Full Form',
        'short_form' => 'Short Form',
    ];

    protected $fillable = [
        'billing_work_item_id',
        'form_type',
        'requested_by_name',
        'requested_by_role_slug',
        'requested_from_panel',
        'patient_full_name',
        'patient_dob',
        'patient_identifier',
        'patient_zip',
        'appointment_date',
        'appointment_time',
        'location_name',
        'provider_name',
        'pms_id',
        'is_pre_registered',
        'subscriber_name',
        'subscriber_dob',
        'subscriber_id',
        'insured_relation',
        'cob',
        'insurance_provider_name',
        'insurance_claim_mailing_address',
        'insurance_company_phone_number',
        'payer_id',
        'effective_date',
        'group_name',
        'group_number',
        'network_status',
        'fee_schedule',
        'plan_type',
        'annual_maximum',
        'annual_maximum_remaining',
        'individual_deductible',
        'individual_deductible_remaining',
        'family_deductible',
        'family_deductible_remaining',
        'is_provider_in_network',
        'plan_renewal_month',
        'future_termination_date',
        'deductible_applies_notes',
        'coverage_diagnostic_deductible_applies',
        'coverage_basic_restorative_deductible_applies',
        'coverage_endodontics_deductible_applies',
        'coverage_periodontics_deductible_applies',
        'coverage_oral_surgery_deductible_applies',
        'coverage_major_restorative_deductible_applies',
        'coverage_orthodontics_deductible_applies',
        'coverage_diagnostic',
        'coverage_preventive',
        'coverage_basic_restorative',
        'coverage_endodontics',
        'coverage_periodontics',
        'coverage_oral_surgery',
        'coverage_major_restorative',
        'coverage_prosthodontics',
        'coverage_implant',
        'plan_provisions',
        'waiting_periods',
        'waiting_period_perio',
        'waiting_period_oral_surgery',
        'waiting_period_crowns',
        'waiting_period_prosthodontics',
        'waiting_period_implant_services',
        'missing_tooth_clause',
        'crowns_paid_on',
        'allowed_same_day_extraction',
        'prosthetic_replacement_period',
        'service_history',
        'history_exams',
        'history_prophylaxis',
        'history_bitewings',
        'history_full_mouth_xray',
        'history_basic_or_major',
        'frequency_regular_oral_exams',
        'frequency_limited_exam',
        'frequency_comprehensive_exam',
        'frequency_exam_shared',
        'frequency_oral_cancer_screening',
        'frequency_oral_cancer_conjunction',
        'frequency_prophylaxis',
        'frequency_bitewings',
        'frequency_full_mouth_pano_shared',
        'frequency_pas',
        'frequency_sealants',
        'frequency_sealants_guideline',
        'frequency_caries_arresting',
        'frequency_fluoride',
        'basic_scaling_root_planing',
        'basic_all_quads_same_visit',
        'basic_perio_maintenance_share_freq',
        'basic_fmd',
        'basic_root_canal',
        'basic_simple_extraction',
        'basic_surgical_extraction',
        'basic_posterior_composites',
        'basic_composites_downgrade',
        'basic_occlusal_guard',
        'major_crowns_downgrade',
        'major_pf_high_noble',
        'major_hydroxyapatite',
        'major_dentures',
        'major_implant',
        'major_implant_abutment',
        'major_implant_crown',
        'major_bone_graft_same_time_implant',
        'major_bone_grafts',
        'ortho_information',
        'ortho_benefit',
        'ortho_retention',
        'ortho_individual_deductible_amount',
        'ortho_lifetime_maximum',
        'ortho_remaining_maximum',
        'ortho_deductibles',
        'ortho_age_limit',
        'verification_date',
        'verified_by',
        'insurance_representative_name',
        'verification_notes',
        'quick_reference',
    ];

    protected function casts(): array
    {
        return [
            'patient_dob' => 'date',
            'appointment_date' => 'date',
            'subscriber_dob' => 'date',
            'effective_date' => 'date',
            'future_termination_date' => 'date',
            'verification_date' => 'date',
            'is_pre_registered' => 'boolean',
            'is_provider_in_network' => 'boolean',
            'annual_maximum' => 'decimal:2',
            'annual_maximum_remaining' => 'decimal:2',
            'individual_deductible' => 'decimal:2',
            'individual_deductible_remaining' => 'decimal:2',
            'family_deductible' => 'decimal:2',
            'family_deductible_remaining' => 'decimal:2',
            'coverage_diagnostic' => 'integer',
            'coverage_preventive' => 'integer',
            'coverage_basic_restorative' => 'integer',
            'coverage_endodontics' => 'integer',
            'coverage_periodontics' => 'integer',
            'coverage_oral_surgery' => 'integer',
            'coverage_major_restorative' => 'integer',
            'coverage_prosthodontics' => 'integer',
            'coverage_implant' => 'integer',
        ];
    }

    public function workItem(): BelongsTo
    {
        return $this->belongsTo(BillingWorkItem::class, 'billing_work_item_id');
    }
}
